CREATE TABLE IF NOT EXISTS public.SUBSCRIBERS(
    SUBSCRIBER_ID VARCHAR(255),
    COUNTRY VARCHAR(255),
    CITY VARCHAR(255),
    DOMAIN VARCHAR(255),
    UNIQUE_KEY_ID VARCHAR(255),
    PUB_KEY_ID VARCHAR(255),
    SIGNING_PUBLIC_KEY VARCHAR(255),
    ENCR_PUBLIC_KEY VARCHAR(255),
    VALID_FROM VARCHAR(255),
    VALID_TO VARCHAR(255),
    STATUS VARCHAR(255),
    CREATED VARCHAR(255),
    UPDATED VARCHAR(255),
    RADIUS VARCHAR(255),
    TYPE VARCHAR(255),
    URL VARCHAR(255)
);